### ISSUE TITLE
python test.py ERROR: Unable to get driver

### ISSUE THREAD

**Issue by evanlu14** [lunixbochs/lorcon#2]
Hello, after I install the pylorcon2, I try to run the test file, but there is something wrong:

```
lzc@lzc-ubuntu:~/Workspace/Git/lorcon/pylorcon2$ python test.py 
testAutoDriver (__main__.PyLorcon2TestCase) ... ERROR
testChannel (__main__.PyLorcon2TestCase) ... ERROR
testFindDriver (__main__.PyLorcon2TestCase) ... ERROR
testGetDriverName (__main__.PyLorcon2TestCase) ... ERROR
testGetVersion (__main__.PyLorcon2TestCase) ... ERROR
testInjection (__main__.PyLorcon2TestCase) ... ERROR
testListDrivers (__main__.PyLorcon2TestCase) ... ERROR
testMAC (__main__.PyLorcon2TestCase) ... ERROR
testTimeout (__main__.PyLorcon2TestCase) ... ERROR
testVap (__main__.PyLorcon2TestCase) ... ERROR

======================================================================
ERROR: testAutoDriver (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testChannel (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testFindDriver (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testGetDriverName (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testGetVersion (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testInjection (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testListDrivers (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testMAC (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testTimeout (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

======================================================================
ERROR: testVap (__main__.PyLorcon2TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 40, in setUp
    self.ctx = PyLorcon2.Context(self.iface)
Lorcon2Exception: Unable to get driver

----------------------------------------------------------------------
Ran 10 tests in 0.001s

FAILED (errors=10)

```

First I thought it was wireless card problem. So I changed line 25 `iface = ''` to point to my another USB wireless card but the result was the same. 
Then I use airmon-ng to switch the wireless card to  monitor mode, but the result was still the same.
Now I doubt the reason is in line 28: `driver = 'mac80211'`, but I don't know how to fix it.
Can you help me?

My OS is ubuntu16.04

**Comment by MRXe** [comment]
Hi,I finally found someone with the same problem . Did you sovle the problem? I want to ask you how to solve it. orz
